# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-17 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='replylog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('friend', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('line', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='fk',
            name='kuakuaid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.replylog'),
        ),
    ]
