# Generated by Django 2.2.6 on 2019-10-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191017_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='sgender',
            field=models.BooleanField(default=True, verbose_name='sgender'),
        ),
        migrations.AlterField(
            model_name='students',
            name='sname',
            field=models.CharField(max_length=20, verbose_name='sname'),
        ),
    ]
